name: bentest2
favicon: null
layout_spectrum: 0.6873004273511469
typography_spectrum: 0.04813520540483296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9048562343232334
  lightness: 0.3900652355514467
  saturation: 0.03840408893302083
  rhythmicContrast: 0.29909655661322176
purpose: []
